name: Daily MAF tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '00 22 * * 6' # Executes Saturday night at 23:00 CET or 00:00 CEST (schedule expressed in UTC).

jobs:
  compile:
    name: Compile MAF
    runs-on: ubuntu-latest
    #  needs: activity-check
    #  if: env.MAF_REPO_ACTIVE == 'true'
    steps:
      # Send a notification to Slack.
      - name: Notify start
        id: slack
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: maf-logs
          status: STARTED
          color: warning
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      # Check out the GitHub repository.
      - name: Checkout the repository
        uses: actions/checkout@v2
      # Compile the code.
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15
      - name: Compile MAF
        run: sbt compile
      # Run _all_ tests in the repository.
      - name: Run utility tests
        run: sbt "maf/test"
      # If failed, update the Slack notification.
      - name: Notify slack fail
        if: failure() || cancelled()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: FAILED
          color: danger
      # Send a notification to Slack on success.
      - name: Notify slack success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: maf-logs
          status: SUCCESS
          color: good
